Repository BalancerMaxis/multisig-ops, pull requests merged in 2023-05, with the labels that each got.

#153 BIP-268: Grant ability to add 3rd party rewards on L2's with new gauges
  .github/workflows/run_auth_gen.yaml
  BIPs/00batched/authorizer/func_desc_by_name.json
  BIPs/00batched/authorizer/governance_template.md
  BIPs/BIP-268/BIP-268.md
  BIPs/BIP-268/README.md
  BIPs/BIP-268/arbitrum.json
  BIPs/BIP-268/function_descriptions.md
  BIPs/BIP-268/gnosis.json
  BIPs/BIP-268/inputs.json
  BIPs/BIP-268/optimism.json
  BIPs/BIP-268/polygon.json
  BIPs/BIP-268/results_address_sorted.md
  BIPs/BIP-268/results_deployment_sorted.md
  tools/python/brownie/helpers/addresses.py
Labels: Generate Authorizer

#160 BIP-274
  BIPs/BIP-274.json
  BIPs/BIP-274.report.txt
Labels: Gauge Payloads

#168 Create BIP-278-279A.json
  BIPs/BIP-278-279A.json
  BIPs/BIP-278-279A.report.txt
  action-scripts/brownie/output.txt
Labels: Gauge Payloads

#172 Create BIP-284.json
  BIPs/BIP-284.json
  BIPs/BIP-284.report.txt
  action-scripts/brownie/output.txt
Labels: Gauge Payloads

#186 W18 fee sweep
  FeeSweep/2023-05-12-arbi.json
  FeeSweep/2023-05-12-eth.json
  FeeSweep/2023-05-12-matic.json
  FeeSweep/feeSweep.json
  FeeSweep/out/2023-05-12-arb.json
  FeeSweep/out/2023-05-12-arb.report.txt
  FeeSweep/out/2023-05-12-cowswap.md
  FeeSweep/out/2023-05-12-eth.json
  FeeSweep/out/2023-05-12-eth.report.txt
  FeeSweep/out/2023-05-12-matic.json
  FeeSweep/out/2023-05-12-matic.report.txt
  tools/python/brownie/pyproject.toml
  tools/python/brownie/requirements.txt
  tools/python/brownie/scripts/maxi_operations/flogFees.py
Labels: Sweep Fees

#181 Create BIP-291.json
  BIPs/BIP-291.json
  BIPs/BIP-291.report.txt
  action-scripts/brownie/.gitignore
  action-scripts/brownie/output.txt
Labels: Gauge Payloads

#179 BIP-290 veALCX Gauge to 10% cap
  BIPs/BIP-290.json
Labels: Gauge Payloads

#174 BIP-289: Add LM multisig roles to add gauges to gauge adder v3
  BIPs/00batched/authorizer/2023-05-05.json
  BIPs/00batched/authorizer/2023-05-05_address_sorted.md
  BIPs/00batched/authorizer/2023-05-05_deployment_sorted.md
  BIPs/00batched/authorizer/2023-05-05_function_descriptions.md
  BIPs/00batched/authorizer/2023-05-05_mainnet.json
  BIPs/BIP-289/BIP-289.md
  BIPs/BIP-289/README.md
  BIPs/BIP-289/function_descriptions.md
  BIPs/BIP-289/inputs.json
  BIPs/BIP-289/mainnet.json
  BIPs/BIP-289/results_address_sorted.md
  BIPs/BIP-289/results_deployment_sorted.md
Labels: Generate Authorizer

#192 Create BIP-292.json
  BIPs/2023-W20/BIP-292.json
  BIPs/2023-W20/BIP-292.report.txt
Labels: Gauge Payloads

#196 BIP-296 A & B
  BIPs/2023-W20/BIP-296A.json
  BIPs/2023-W20/BIP-296A.report.txt
  BIPs/2023-W22/BIP-296B.json
  BIPs/2023-W22/BIP-296B.report.txt
Labels: Gauge Payloads

#197 Create BIP-297.json
  .github/workflows/run_gauge_payload_report.yaml
  BIPs/2023-W20/BIP-297.json
  BIPs/2023-W20/BIP-297.report.txt
  action-scripts/brownie/scripts/get_gauge_mappings.py
  action-scripts/brownie/scripts/rerun_all_gauge_reports.py
Labels: Gauge Payloads

#202 2020-W20 Payload Merge
  .github/workflows/merge_json.yaml
  BIPs/00batched/2023-W20/1-0x10A19e7eE7d7F8a52822f6817de8ea18204F2e4f.json
  BIPs/00batched/2023-W20/1-0x10A19e7eE7d7F8a52822f6817de8ea18204F2e4f.report.txt
  BIPs/00batched/2023-W20/1-0xc38c5f97B34E175FFd35407fc91a937300E33860.json
  BIPs/00batched/2023-W20/1-0xc38c5f97B34E175FFd35407fc91a937300E33860.report.txt
  BIPs/00batched/2023-W20/42161-0xaF23DC5983230E9eEAf93280e312e57539D098D0.json
Labels: Gauge Payloads

#208 Create BIP-305.json
  BIPs/00batched/2023-W20/1-0x10A19e7eE7d7F8a52822f6817de8ea18204F2e4f.report.txt
  BIPs/00batched/2023-W20/1-0xc38c5f97B34E175FFd35407fc91a937300E33860.report.txt
  BIPs/2023-W21/BIP-305.json
  BIPs/2023-W21/BIP-305.report.txt
  action-scripts/brownie/scripts/get_gauge_mappings.py
  action-scripts/brownie/scripts/rerun_all_gauge_reports.py
Labels: Gauge Payloads

#209 Create BIP-307.json
  BIPs/00batched/2023-W20/1-0xc38c5f97B34E175FFd35407fc91a937300E33860.report.txt
  BIPs/2023-W21/BIP-307.json
  BIPs/2023-W21/BIP-307.report.txt
Labels: Gauge Payloads
