Repository BalancerMaxis/multisig-ops, pull requests merged in 2023-07, with the labels that each got.

#323 fix: skip transactions without contractInputsValues
  action-scripts/brownie/scripts/report_gauges.py
Labels: fix

#333 BIP-350: Balancer Grants DAO Service Provider Proposal Q3 2023
  BIPs/2023-W27/BIP-350.json
  BIPs/2023-W27/BIP-350.report.txt
Labels: BIP JSON, BIP-JSON

#334 BIP351: Funding Proposal for the Balancer OpCo - Product Team
  BIPs/2023-W27/BIP-351.json
  BIPs/2023-W27/BIP-351.report.txt
Labels: BIP JSON, BIP-JSON

#335 BIP-352: Funding Proposal for the Integrations Team (Three Rocks)
  BIPs/2023-W30/BIP-352A.json
  BIPs/2023-W30/BIP-352A.report.txt
  BIPs/2023-W39/BIP-352B.json
  BIPs/2023-W39/BIP-352B.report.txt
Labels: BIP JSON, BIP-JSON

#342 Fee Sweep 2023-07-07
  Bribs/2023-07-07.csv
  Bribs/whatsGoingON.txt
  FeeSweep/2023-07-07-eth.json
  FeeSweep/out/2023-07-07-cowswap-1strun.md
  FeeSweep/out/2023-07-07-cowswap.md
  FeeSweep/out/2023-07-07-eth.json
  FeeSweep/out/2023-07-07-eth.report-1strun.txt
  FeeSweep/out/2023-07-07-eth.report.txt
  tools/python/brownie/interfaces/hiddenhand/IBribeMarket.sol
  tools/python/brownie/interfaces/hiddenhand/IBribeVault.sol
  tools/python/brownie/scripts/maxi_operations/bribe_ecosystems.py
Labels: Sweep Fees

#346 Rework reporting and merge flow
  .github/workflows/merge_json.yaml
  .github/workflows/process_every_payload.yaml
  .github/workflows/reformat_json_files.yml
  .github/workflows/run_gauge_payload_report_v2.yaml
  .github/workflows/run_reports_reusable.yaml
  .github/workflows/validate_bips.yaml
  BIPs/4269-W69/test/BIP-303/BIP-303.md
  BIPs/4269-W69/test/BIP-303/BIP-303A.json
  BIPs/4269-W69/test/BIP-303/BIP-303B.json
  BIPs/4269-W69/test/BIP-303/BIP-303C.json
  BIPs/4269-W69/test/BIP-303/README.md
  BIPs/4269-W69/test/BIP-303/function_descriptions.md
  BIPs/4269-W69/test/BIP-303/inputs.json
  BIPs/4269-W69/test/BIP-303/results_address_sorted.md
  BIPs/4269-W69/test/BIP-303/results_deployment_sorted.md
  BIPs/4269-W69/test/BIP-303/zkevm.json
  BIPs/4269-W69/test/BIP-314 july.json
  BIPs/4269-W69/test/BIP-314 july.report.txt
  BIPs/4269-W69/test/BIP-340B.json
  BIPs/4269-W69/test/BIP-340B.report.txt
  BIPs/4269-W69/test/BIP-343/arbitrum.json
  BIPs/4269-W69/test/BIP-343/avalanche.json
  BIPs/4269-W69/test/BIP-343/gnosis.json
  BIPs/4269-W69/test/BIP-343/inputs.json
  BIPs/4269-W69/test/BIP-343/mainnet.json
  BIPs/4269-W69/test/BIP-343/optimism.json
  BIPs/4269-W69/test/BIP-343/polygon.json
  BIPs/4269-W69/test/BIP-343/zkevm.json
  BIPs/4269-W69/test/BIP-344.json
  BIPs/4269-W69/test/BIP-344.report.txt
  BIPs/4269-W69/test/BIP-345.json
  BIPs/4269-W69/test/BIP-345.report.txt
  BIPs/4269-W69/test/BIP-346.json
  BIPs/4269-W69/test/BIP-346.report.txt
  BIPs/4269-W69/test/BIP-347.json
  BIPs/4269-W69/test/BIP-348.json
  action-scripts/brownie/.gitignore
  action-scripts/brownie/scripts/report_gauges.py
  action-scripts/brownie/scripts/rerun_all_gauge_reports.py
  action-scripts/brownie/scripts/validate_bip.py
Labels: Assigned

#358 BIP-353 CSPv5 permission granting
  .github/workflows/build_permissions_bip.yaml
  BIPs/00batched/authorizer/2023-07-12.json
  BIPs/00batched/authorizer/gen_gov_md.sh
  BIPs/2023-W28/BIP-353/BIP-353.md
  BIPs/2023-W28/BIP-353/README.md
  BIPs/2023-W28/BIP-353/arbitrum.json
  BIPs/2023-W28/BIP-353/avalanche.json
  BIPs/2023-W28/BIP-353/function_descriptions.md
  BIPs/2023-W28/BIP-353/gnosis.json
  BIPs/2023-W28/BIP-353/inputs.json
  BIPs/2023-W28/BIP-353/mainnet.json
  BIPs/2023-W28/BIP-353/optimism.json
  BIPs/2023-W28/BIP-353/polygon.json
  BIPs/2023-W28/BIP-353/results_address_sorted.md
  BIPs/2023-W28/BIP-353/results_deployment_sorted.md
  BIPs/2023-W28/BIP-353/zkevm.json
  action-scripts/gen_add_permissions_payload.py
Labels: Generate Authorizer

#365 BIP-357: Enable GHO/LUSD Gauge [Ethereum]
  BIPs/2023-W28/BIP-357.json
  BIPs/2023-W28/BIP-357.report.txt
Labels: Gauge Payloads

#366 BIP-358: Enable GHO/wstETH Gauge [Ethereum]
  BIPs/2023-W28/BIP-358.json
  BIPs/2023-W28/BIP-358.report.txt
Labels: Gauge Payloads

#367 BIP-359: Enable GHO/OHM Gauge [Ethereum]
  BIPs/2023-W28/BIP-359.json
  BIPs/2023-W28/BIP-359.report.txt
Labels: Gauge Payloads

#368 BIP-360: Enable GHO/bb-a-USD Gauge [Ethereum]
  BIPs/2023-W28/BIP-360.json
  BIPs/2023-W28/BIP-360.report.txt
Labels: Gauge Payloads

#369 BIP-361: Enable GHO/MAI Gauge [Ethereum]
  BIPs/2023-W28/BIP-361.json
  BIPs/2023-W28/BIP-361.report.txt
Labels: Gauge Payloads

#380 BIP-367-Update-Addresses-For-Emergency-Multisigs
  BIPs/2023-W29/BIP-367-1.json
  BIPs/2023-W29/BIP-367-100.json
  BIPs/2023-W29/BIP-367-1100.json
  BIPs/2023-W29/BIP-367-137.json
  BIPs/2023-W29/BIP-367-42161.json
  BIPs/2023-W29/BIP367-10.json
Labels: EmergencyDAO
