Repository BalancerMaxis/multisig-ops, pull requests merged in 2023-06, with the labels that each got.

#254 2023 W23 fee handling
  BIPs/00batched/2023-W22/1-anySafeWillDo.json
  Bribs/2023-06-09.csv
  Bribs/partner_lm/gear/2023-06-09-1m-gear.json
  Bribs/partner_lm/gear/2023-06-09.json
  FeeSweep/2023-06-09-eth-firstpass.json
  FeeSweep/2023-06-09-eth.json
  FeeSweep/2023-06-09-matic.json
  FeeSweep/out/2023-06-09-cowswap.md
  FeeSweep/out/2023-06-09-eth.json
  FeeSweep/out/2023-06-09-eth.report.txt
  FeeSweep/out/2023-06-09-matic.json
  FeeSweep/out/2023-06-09-matic.report.txt
  tools/python/brownie/great_ape_safe/ape_api/cow.py
  tools/python/brownie/great_ape_safe/great_ape_safe.py
  tools/python/brownie/helpers/addresses.py
  tools/python/brownie/scripts/maxi_operations/bribe_ecosystems.py
  tools/python/brownie/scripts/maxi_operations/flogFees.py
  tools/python/claim_and_brib_gear.py
Labels: Sweep Fees

#265 BIP-327: Enable rETH / bb-a-WETH Gauge
  BIPs/2023-W24/BIP-327.json
  BIPs/2023-W24/BIP-327.report.txt
Labels: Gauge Payloads

#268 BIP-330: Enable OHM/bb-a-DAI Gauge
  BIPs/2023-W24/BIP-330.json
  BIPs/2023-W24/BIP-330.report.txt
Labels: Gauge Payloads

#267 BIP-329: Enable ACID/WETH Gauge
  BIPs/2023-W24/BIP-329.json
  BIPs/2023-W24/BIP-329.report.txt
Labels: Gauge Payloads

#266 BIP-328: Enable Initial zkEVM Gauges
  BIPs/2023-W24/BIP-328.json
  BIPs/2023-W24/BIP-328.report.txt
  action-scripts/brownie/scripts/report_gauge_add.py
Labels: Gauge Payloads

#283 feat: fail loud on BIP json validation
  action-scripts/merge_pr_jsons.py
Labels: enhancement

#286 BIP-336: Enable uniETH/wETH Gauge [Ethereum] w/ 2% emissions cap
  BIPs/2023-W25/BIP336.json
  BIPs/2023-W25/BIP336.report.txt
Labels: Gauge Payloads

#287 BIP-337: Enable OHM / bb-a-wETH Gauge [Ethereum]
  BIPs/2023-W25/BIP-337.json
  BIPs/2023-W25/BIP-337.report.txt
Labels: Gauge Payloads

#288 BIP-338: Enable 55/45 auraBAL/wstETH Gauge [Arbitrum]
  BIPs/2023-W25/BIP-338.json
  BIPs/2023-W25/BIP-338.report.txt
Labels: Gauge Payloads

#290 BIP-340: Migrate vETH StablePool Gauge [Ethereum]
  BIPs/2023-W25/BIP-340A.json
  BIPs/2023-W25/BIP-340A.report.txt
  BIPs/2023-W26/BIP-340B.json
  BIPs/2023-W26/BIP-340B.report.txt
Labels: Gauge Payloads

#302 Automate report on merged json
  .github/workflows/merge_json.yaml
Labels: enhancement

#304 BIP-344: Activate Optimism Initial Pool Gauges [Optimism]
  BIPs/2023-W26/BIP-344.json
  BIPs/2023-W26/BIP-344.report.txt
Labels: Gauge Payloads

#305 BIP-345: Enable wstETH/WETH Gauge [Optimism]
  BIPs/2023-W26/BIP-345.json
  BIPs/2023-W26/BIP-345.report.txt
Labels: Gauge Payloads

#306 BIP-346: Enable wstETH/WETH Gauge w/ 10% cap [Optimism]
  BIPs/2023-W26/BIP-346.json
  BIPs/2023-W26/BIP-346.report.txt
Labels: Gauge Payloads

#303 BIP-343: Grant emergencyDAO disable recovery mode on Weighted and ComposableStable pools
  BIPs/2023-W26/BIP-343/arbitrum.json
  BIPs/2023-W26/BIP-343/avalanche.json
  BIPs/2023-W26/BIP-343/gnosis.json
  BIPs/2023-W26/BIP-343/inputs.json
  BIPs/2023-W26/BIP-343/mainnet.json
  BIPs/2023-W26/BIP-343/optimism.json
  BIPs/2023-W26/BIP-343/polygon.json
  BIPs/2023-W26/BIP-343/zkevm.json
  BIPs/BIP-343/BIP-343.md
Labels: Generate Authorizer
