Repository BalancerMaxis/multisig-ops, pull requests merged in 2023-04, with the labels that each got.

#125 Sweep, sell and brib fees: 31-03-2023 (week 14)
  Bribs/2023-03-31.csv
  FeeSweep/2023-03-31-arb.json
  FeeSweep/2023-03-31-eth.json
  FeeSweep/2023-03-31-matic.json
  FeeSweep/out/2023-03-31-arb.json
  FeeSweep/out/2023-03-31-arb.report.txt
  FeeSweep/out/2023-03-31-eth.json
  FeeSweep/out/2023-03-31-eth.report.txt
  FeeSweep/out/2023-03-31-matic.json
  FeeSweep/out/2023-03-31-matic.report.txt
  tools/python/brownie/scripts/maxi_operations/bribe_ecosystems.py
  tools/python/brownie/scripts/maxi_operations/flogFees.py
Labels: Sweep Fees

#142 BIP-253: Grant permissions on managed pool v2, composable v4, weighted v4
  BIPs/BIP-253/BIP-253.md
  BIPs/BIP-253/README.md
  BIPs/BIP-253/arbitrum.json
  BIPs/BIP-253/function_descriptions.md
  BIPs/BIP-253/gnosis.json
  BIPs/BIP-253/inputs.json
  BIPs/BIP-253/mainnet.json
  BIPs/BIP-253/optimism.json
  BIPs/BIP-253/polygon.json
  BIPs/BIP-253/results_address_sorted.md
  BIPs/BIP-253/results_deployment_sorted.md
  tools/python/brownie/helpers/addresses.py
Labels: Generate Authorizer

#146 BIP-256-261A: Add gauges
  BIPs/BIP-256-261A.json
Labels: Gauge Payloads

#148 BIP-265-267 Add additional gauges
  BIPs/BIP-265-267.json
Labels: Gauge Payloads

#147 BIP-261B Kill Gauges
  BIPs/BIP-261B.json
Labels: Gauge Payloads

#155 Testing more robust reports with commited output files.
  .github/workflows/run_gauge_payload_report.yaml
  BIPs/BIP-262-L2-gauge-migration/BIP-262A.report.txt
  BIPs/BIP-262/BIP-262A.json
  BIPs/BIP-262/BIP-262A.report.txt
  BIPs/BIP-262/BIP-262B.json
  BIPs/BIP-262/BIP-262B.report.txt
  BIPs/BIP-262/BIP-262C.json
  BIPs/BIP-262/BIP-262C.report.txt
  BIPs/BIP-262/BIP-262D.json
  BIPs/BIP-262/BIP-262D.report.txt
  action-scripts/brownie/abis/Authorizer.json
  action-scripts/brownie/abis/GearAirdropDistributor.json
  action-scripts/brownie/abis/IAuraBriber.json
  action-scripts/brownie/abis/IBalPool.json
  action-scripts/brownie/abis/IBalancerBribe.json
  action-scripts/brownie/abis/IBalancerMinter.json
  action-scripts/brownie/abis/IChildChainStreamer.json
  action-scripts/brownie/abis/IComposibleStable.json
  action-scripts/brownie/abis/IRewardsOnlyGauge.json
  action-scripts/brownie/abis/IVault.json
  action-scripts/brownie/abis/IWeightedPoolFactoryV4.json
  action-scripts/brownie/output.txt
  action-scripts/brownie/requirements-actions.txt
  action-scripts/brownie/scripts/get_gauge_mappings.py
Labels: Gauge Payloads

#161 W17 fee handling
  Bribs/2023-04-28.csv
  FeeSweep/2023-04-28-arbi.json
  FeeSweep/2023-04-28-eth.json
  FeeSweep/2023-04-28.matic.json
  FeeSweep/out/2023-04-28-arb.json
  FeeSweep/out/2023-04-28-arb.report.txt
  FeeSweep/out/2023-04-28-eth.json
  FeeSweep/out/2023-04-28-eth.report.txt
  FeeSweep/out/2023-04-28-matic.json
  FeeSweep/out/2023-04-28-matic.report.txt
  tools/python/brownie/scripts/maxi_operations/bribe_ecosystems.py
  tools/python/brownie/scripts/maxi_operations/flogFees.py
  tools/python/sweepFees.py
Labels: Sweep Fees
